export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER',
};

export const userConstants = {
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
  GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
  GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',

  GET_TEACHERS_REQUEST: 'GET_TEACHERS_REQUEST',
  GET_TEACHERS_SUCCESS: 'GET_TEACHERS_SUCCESS',
  GET_TEACHERS_FAILURE: 'GET_TEACHERS_FAILURE',

  DELETE_USER_REQUEST: ' DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: ' DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: ' DELETE_USER_FAILURE',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
};

export const courseConstants = {
  ADD_COURSE_REQUEST: 'ADD_COURSE_REQUEST',
  ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
  ADD_COURSE_FAILURE: 'ADD_COURSE_FAILURE',

  GET_COURSES_REQUEST: 'GET_COURSES_REQUEST',
  GET_COURSES_SUCCESS: 'GET_COURSES_SUCCESS',
  GET_COURSES_FAILURE: 'GET_COURSES_FAILURE',

  GET_COURSE_BY_SLUG: 'GET_COURSE_BY_SLUG',
};
export const themeConstants = {
  GET_THEMES_REQUEST: 'GET_THEMES_REQUEST',
  GET_THEMES_SUCCESS: 'GET_THEMES_SUCCESS',
  GET_THEMES_FAILURE: 'GET_THEMES_FAILURE',
};
